name: Lint and Compile

on:
  release:
    types:
      - created
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11
      - run: pip install -U pip setuptools flake8
      - run: pip install -e .
      - run: python -m flake8
  build:
    runs-on: ubuntu-22.04
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.11
      - run: pip install -U pip setuptools build
      - run: python -m build
      - uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ github.event.repository.name }}
          path: dist/*
